spring:
  application:
    name: spring-cloud-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/rishabh7774/spring-cloud-config-server

server:
  port: 8888
management:
  security:
    enabled: false



